import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import SideBar from '@/components/menu/SideBar'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            inter.className,
            'min-h-screen grid grid-flow-col grid-cols-[max-content,1fr]'
          )}
        >
          <SideBar />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  )
}
